apiVersion: v1
kind: Service
metadata:
  name: profile-app-service
  labels:
    app: profile
spec:
  selector:
    app: profile-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: profile-app-monitoring-service
  labels:
    app: profile-app-metrics
spec:
  selector:
    app: profile-app
  ports:
    - protocol: TCP
      port: 9093
      targetPort: web
      name: metrics
  type: ClusterIP
